# version: '3'

services:
  backend:
    container_name: backend
    restart: always
    build: ./backend
    environment:
      - NODE_ENV=development
    env_file:
      - ./backend/.env # Ruta específica al archivo .env
    command: npm run dev
    ports:
      - "3001:3001"

  frontend:
    container_name: frontend
    restart: always
    build: ./frontend
    ports:
      - "5173:5173"



